### ISSUE TITLE
Data format h5 not recognised,and 10x wanted (but I set format="10x"

### ISSUE THREAD

**Issue by yejg2017** [scvae/scvae#9] opened 2019-09-05 01:22 UTC
Hi,
When I feed the single cell 10X data in .h5 format,and I got the error:ValueError: Data format h5 not recognised.How can I solve this issue?

**Comment by chgroenbech** [comment] 2019-11-04 14:00
Duplicate of #3

**Closed** 2019-11-04 14:23 UTC
